# Generated by Django 4.2.27 on 2026-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_problemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allow_virtual_participation',
            field=models.BooleanField(default=True, help_text='Allow users to participate virtually after the contest ends.', verbose_name='allow virtual participation'),
        ),
    ]
